name = "pgmq-admin"
organization = "io.github.matejcerny"
scalaVersion = "3.8.2"
homepage = "https://github.com/matejcerny/pgmq-admin"
licenses = ["Apache2"]
versionScheme = "early-semver"
developers = [
  {
    id = "matejcerny"
    name = "Matej Cerny"
    email = "cerny.matej@gmail.com"
    url = "https://matejcerny.cz/en/"
  }
]

scalacOptions = [
  "-explain"
]

versions {
  cats = "3.6.3"
  http4s = "0.23.30"
  skunk = "0.6.5"
  pgmq4s = "0.5.0"
  tapir = "1.9.9"
  scribe = "3.13.2"
  scalatags = "0.12.0"
}

modules {
  pgmq4s = "io.github.matejcerny"
  tapir = "com.softwaremill.sttp.tapir"
  scribe = "com.outr"
}

dependencies {
  shared {
    scala = [
      "org.typelevel:cats-effect:"${versions.cats},
      "org.http4s:http4s-ember-server:"${versions.http4s},
      "org.tpolecat:skunk-core:"${versions.skunk},
      ${modules.pgmq4s}":pgmq4s-core:"${versions.pgmq4s},
      ${modules.pgmq4s}":pgmq4s-skunk:"${versions.pgmq4s},
      ${modules.pgmq4s}":pgmq4s-jsoniter:"${versions.pgmq4s},
      ${modules.tapir}":tapir-core:"${versions.tapir},
      ${modules.tapir}":tapir-http4s-server:"${versions.tapir},
      ${modules.scribe}":scribe:"${versions.scribe},
      "com.lihaoyi:scalatags:"${versions.scalatags}
    ]
  }
  jvm {
    scala = [${modules.scribe}":scribe-slf4j:"${versions.scribe}]
  }
}

# Test dependencies (automatically added with Test scope)
# testDependencies = [
#   "org.scalatest:scalatest:3.2.19"
# ]
