name = "pgmq-admin"
organization = "io.github.matejcerny"
scalaVersion = "3.8.3"
homepage = "https://github.com/matejcerny/pgmq-admin"
licenses = ["Apache2"]
versionScheme = "early-semver"
developers = [
  {
    id = "matejcerny"
    name = "Matej Cerny"
    email = "cerny.matej@gmail.com"
    url = "https://matejcerny.cz/en/"
  }
]

scalacOptions = ["-explain"]
resolvers = [{name = "Sonatype Central Snapshots", url = "https://central.sonatype.com/repository/maven-snapshots/"}]

versions {
  http4s = "0.23.34"
  pgmq4s = "0.12.0"
  tapir = "1.13.19"
  scribe = "3.19.0"
  scalatags = "0.13.1"
}

modules {
  pgmq4s = "io.github.matejcerny"
  tapir = "com.softwaremill.sttp.tapir"
  scribe = "com.outr"
}

dependencies {
  shared.scala = [
    "org.http4s:http4s-ember-server:"${versions.http4s},
    ${modules.pgmq4s}":pgmq4s-skunk:"${versions.pgmq4s},
    ${modules.pgmq4s}":pgmq4s-jsoniter:"${versions.pgmq4s},
    ${modules.tapir}":tapir-core:"${versions.tapir},
    ${modules.tapir}":tapir-http4s-server:"${versions.tapir},
    ${modules.scribe}":scribe:"${versions.scribe},
    "com.lihaoyi:scalatags:"${versions.scalatags}
  ]
  jvm.scala = [${modules.scribe}":scribe-slf4j:"${versions.scribe}]
}
